# Generated by Django 4.1.4 on 2023-01-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='phone number'),
        ),
    ]
