# Generated by Django 4.1.4 on 2023-02-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_parent_child_parent_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
    ]
