# Generated by Django 4.1.6 on 2023-02-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone'),
        ('schedule', '0003_alter_classgroup_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='student',
        ),
        migrations.AddField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(related_name='lesson', to='users.student'),
        ),
    ]
