# Generated by Django 4.1.4 on 2023-01-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_classgroup_year_lesson_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='pupil',
        ),
    ]
