# Generated by Django 4.1.6 on 2023-02-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone'),
        ('schedule', '0004_remove_lesson_student_lesson_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='lesson', to='users.student'),
        ),
    ]
