# Generated by Django 4.1.4 on 2023-01-16 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0004_remove_lesson_pupil'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pupil',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pupil', to=settings.AUTH_USER_MODEL),
        ),
    ]
