# Generated by Django 4.1.4 on 2023-02-05 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_initial'),
        ('logbook', '0002_alter_attendance_student_alter_comment_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='attendances',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='comments',
        ),
        migrations.AddField(
            model_name='grade',
            name='type',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='logbook',
            name='attendance',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('E', 'Excused')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='logbook',
            name='comment',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='logbook',
            name='lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='logbook', to='schedule.lesson'),
        ),
        migrations.AddField(
            model_name='logbook',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='logbook', to='schedule.subject'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='grades',
            field=models.ManyToManyField(default=None, related_name='logbook', to='logbook.grade'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
