# Generated by Django 4.1.4 on 2023-02-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_remove_logbook_grades_logbook_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='grade',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
