# Generated by Django 4.1.4 on 2023-02-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_alter_logbook_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='grade',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
