# Generated by Django 4.1.6 on 2023-02-16 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone'),
        ('logbook', '0006_alter_logbook_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook', to='users.student'),
        ),
    ]
